### ISSUE TITLE
Error editable_launch.launch 

### ISSUE THREAD

**Issue by atahirkarasahin** [arplaboratory/RotorTM#8]
First of all, thank you to the rotorTM team. I am using Ubuntu 18.04 and ROS melodic. The error I get after running $ roslaunch rotor_tm editable_launch.launch is in the photos. In addition, there is information about the conda container environment in the photos.

![rotor_tm_error](https://github.com/arplaboratory/RotorTM/assets/36992507/1f065299-a217-44c6-98d3-3807ca2130b1)
![rotor_tm_error2](https://github.com/arplaboratory/RotorTM/assets/36992507/9cd0df6d-aea8-4998-aeee-48d8373dadc6)

**Comment by lguanrui** [comment]
Hi Ali, 

After discussion with my colleagues, we think that this is due to the fact that you are trying to run RotorTM within the conda environment and it might not be able to run the ROS you install locally appropriately. 

One possible solution is to follow the guide here: https://robostack.github.io/GettingStarted.html
to install ROS in your conda environment. Can you try this and let me know how it goes? Thanks!

**Comment by atahirkarasahin** [comment]
Hi Guanrui,

I created a new environment using miniforge and installed the mamba. After running again $ roslaunch rotor_tm editable_launch.launch the error I get is as in the photos. Thanks!

![mamba_error_3](https://github.com/arplaboratory/RotorTM/assets/36992507/8acff919-13db-45b6-a489-b12798d789d1)
![mamba_error_4](https://github.com/arplaboratory/RotorTM/assets/36992507/edc776f0-9c72-471f-8124-7f4c864c7533)

**Comment by lguanrui** [comment]
Hi Ali, sorry for the late reply! I have updated the simulator. Can you pull the latest version? It should resolve the error you have.

**Comment by atahirkarasahin** [comment]
I keep getting errors. Attached are the errors after the new version. 

![Screenshot from 2023-12-06 18-39-31](https://github.com/arplaboratory/RotorTM/assets/36992507/2851acc3-1f0a-4d3a-9576-9d5b1d1e793c)

**Comment by atahirkarasahin** [comment]
I experimented on Windows 10 using the Miniforge-pypy3 package distribution for RoboStack. This time it worked. But I still can't get it to work on ubuntu 18.04 despite doing the same things.

<img width="959" alt="test4" src="https://github.com/arplaboratory/RotorTM/assets/36992507/5a1da2ed-7e4f-4ba4-8038-0fffb40b33b6">

**Comment by lguanrui** [comment]
Hi Ali, the latest errors you showed seem to be a Python version issue in your conda environment. The errors happened when you import the numpy library. 

The discussion [here](https://stackoverflow.com/questions/52889746/cant-import-annotations-from-future) and the documentation [here](https://peps.python.org/pep-0563/#enabling-the-future-behavior-in-python-3-7) shows that the line should work starting from Python 3.7.
